name: zynk
description: "Zynk is an intuitive and engaging mobile application designed to
  help users share meaningful moments and spread joy through simple, yet
  powerful features. The app provides a seamless experience with a beautiful
  interface that encourages users to connect with their friends and loved ones,
  sharing photos, memories, and experiences in a fun and creative way."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  camera: ^0.11.1
  cloud_firestore: ^5.6.5
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  firebase_storage: ^12.4.4
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_native_splash: ^2.4.4
  fpdart: ^1.1.1
  get: ^4.7.2
  google_fonts: ^6.2.1
  google_sign_in: ^6.3.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  lottie: ^3.3.1
  path_provider: ^2.1.5
  share_plus: ^10.1.4
  shared_preferences: ^2.5.2
  supabase_flutter: ^2.8.4
  video_compress: ^3.1.4
  video_player: ^2.9.3

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/zynk_app_logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animation/
    - .env

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/zynk_app_logo.png
  android: true
  ios: true
  web: false
  fullscreen: true
  android_gravity: center

  android_12:
    image: assets/images/zynk_app_logo.png
    icon_background_color: "#ffffff"
    image_gravity: center
